// @generated by buffa-codegen. DO NOT EDIT.
// source: mediatime05/test/clip.proto

#[derive(Clone, Debug, Default)]
pub struct ClipView<'a> {
    /// Field 1: `range`
    pub range: ::buffa::MessageFieldView<
        ::mediatime::wire::__buffa::view::TimeRangeView<'a>,
    >,
    /// Field 2: `at`
    pub at: ::buffa::MessageFieldView<
        ::mediatime::wire::__buffa::view::TimestampView<'a>,
    >,
    /// Field 3: `timebase`
    pub timebase: ::buffa::MessageFieldView<
        ::mediatime::wire::__buffa::view::TimebaseView<'a>,
    >,
    /// Field 4: `cuts`
    pub cuts: ::buffa::RepeatedView<
        'a,
        ::mediatime::wire::__buffa::view::TimeRangeView<'a>,
    >,
    /// Field 5: `marks` (map)
    pub marks: ::buffa::MapView<
        'a,
        &'a str,
        ::mediatime::wire::__buffa::view::TimestampView<'a>,
    >,
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> ::buffa::MessageView<'a> for ClipView<'a> {
    type Owned = super::super::Clip;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.range.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.range = ::buffa::MessageFieldView::set(
                            <::mediatime::wire::__buffa::view::TimeRangeView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.at.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.at = ::buffa::MessageFieldView::set(
                            <::mediatime::wire::__buffa::view::TimestampView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.timebase.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.timebase = ::buffa::MessageFieldView::set(
                            <::mediatime::wire::__buffa::view::TimebaseView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        ::mediatime::wire::__buffa::view::TimeRangeView,
                    >(),
                )?;
                view.cuts
                    .push(
                        <::mediatime::wire::__buffa::view::TimeRangeView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let entry_bytes = ::buffa::types::borrow_bytes(&mut cur)?;
                let mut entry_cur: &'a [u8] = entry_bytes;
                let mut key = "";
                let mut val = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&key)
                        + ::buffa::__private::element_footprint(&val),
                )?;
                while !entry_cur.is_empty() {
                    let entry_tag = ::buffa::encoding::Tag::decode(&mut entry_cur)?;
                    match entry_tag.field_number() {
                        1 => {
                            ::buffa::encoding::check_wire_type(
                                entry_tag,
                                ::buffa::encoding::WireType::LengthDelimited,
                            )?;
                            key = ::buffa::types::borrow_str(&mut entry_cur)?;
                        }
                        2 => {
                            ::buffa::encoding::check_wire_type(
                                entry_tag,
                                ::buffa::encoding::WireType::LengthDelimited,
                            )?;
                            let __sub_ctx = ctx.descend()?;
                            let sub = ::buffa::types::borrow_bytes(&mut entry_cur)?;
                            <::mediatime::wire::__buffa::view::TimestampView as ::buffa::MessageView>::merge_into_view(
                                &mut val,
                                sub,
                                __sub_ctx,
                            )?;
                        }
                        _ => {
                            ::buffa::encoding::skip_field_depth(
                                entry_tag,
                                &mut entry_cur,
                                ctx.depth(),
                            )?;
                        }
                    }
                }
                view.marks.push(key, val);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                let span_len = before_tag.len() - cur.len();
                view.__buffa_unknown_fields.push_record(before_tag, span_len, ctx)?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Clip, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Clip, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Clip {
            range: match self.range.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        ::mediatime::wire::TimeRange,
                        ::buffa::Inline<::mediatime::wire::TimeRange>,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            at: match self.at.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        ::mediatime::wire::Timestamp,
                        ::buffa::Inline<::mediatime::wire::Timestamp>,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            timebase: match self.timebase.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        ::mediatime::wire::Timebase,
                        ::buffa::Inline<::mediatime::wire::Timebase>,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            cuts: self
                .cuts
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            marks: self
                .marks
                .iter()
                .map(|(k, v)| {
                    ::core::result::Result::<
                        _,
                        ::buffa::DecodeError,
                    >::Ok((k.to_string(), v.to_owned_from_source(__buffa_src)?))
                })
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            __buffa_unknown_fields: self.__buffa_unknown_fields.to_owned()?.into(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for ClipView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.range.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.range.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.at.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.at.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.timebase.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.timebase.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.cuts {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        #[allow(clippy::for_kv_map)]
        for (k, v) in &self.marks {
            let entry_size: u64 = 1u64 + ::buffa::types::string_encoded_len(k) as u64
                + 1u64
                + {
                    let __slot = __cache.reserve();
                    let inner = v.compute_size(__cache);
                    __cache.set(__slot, inner);
                    ::buffa::encoding::varint_len(inner as u64) as u64 + inner as u64
                };
            size += 1u64 + ::buffa::encoding::varint_len(entry_size) as u64 + entry_size;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.range.is_set() {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.range.write_to(__cache, buf);
        }
        if self.at.is_set() {
            ::buffa::types::put_len_delimited_header(
                2u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.at.write_to(__cache, buf);
        }
        if self.timebase.is_set() {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.timebase.write_to(__cache, buf);
        }
        for v in &self.cuts {
            ::buffa::types::put_len_delimited_header(
                4u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for (k, v) in &self.marks {
            let __v_len = __cache.consume_next();
            let entry_size: u64 = 1u64 + ::buffa::types::string_encoded_len(k) as u64
                + 1u64
                + (::buffa::encoding::varint_len(__v_len as u64) as u64
                    + __v_len as u64);
            ::buffa::encoding::Tag::new(
                    5u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(entry_size, buf);
            ::buffa::encoding::Tag::new(
                    1u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(k, buf);
            ::buffa::encoding::Tag::new(
                    2u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(__v_len as u64, buf);
            v.write_to(__cache, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
}
impl<'a> ::buffa::MessageName for ClipView<'a> {
    const PACKAGE: &'static str = "mediatime05.test";
    const NAME: &'static str = "Clip";
    const FULL_NAME: &'static str = "mediatime05.test.Clip";
    const TYPE_URL: &'static str = "type.googleapis.com/mediatime05.test.Clip";
}
::buffa::impl_default_view_instance!(ClipView);
::buffa::impl_view_reborrow!(ClipView);
/** Self-contained, `'static` owned view of a `Clip` message.

 Wraps [`::buffa::OwnedView`]`<`[`ClipView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`ClipView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct ClipOwnedView(::buffa::OwnedView<ClipView<'static>>);
impl ClipOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(ClipOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ClipOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Clip,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(ClipOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`ClipView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &ClipView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Clip {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `range`
    #[must_use]
    pub fn range(
        &self,
    ) -> &::buffa::MessageFieldView<
        ::mediatime::wire::__buffa::view::TimeRangeView<'_>,
    > {
        &self.0.reborrow().range
    }
    /// Field 2: `at`
    #[must_use]
    pub fn at(
        &self,
    ) -> &::buffa::MessageFieldView<
        ::mediatime::wire::__buffa::view::TimestampView<'_>,
    > {
        &self.0.reborrow().at
    }
    /// Field 3: `timebase`
    #[must_use]
    pub fn timebase(
        &self,
    ) -> &::buffa::MessageFieldView<::mediatime::wire::__buffa::view::TimebaseView<'_>> {
        &self.0.reborrow().timebase
    }
    /// Field 4: `cuts`
    #[must_use]
    pub fn cuts(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        ::mediatime::wire::__buffa::view::TimeRangeView<'_>,
    > {
        &self.0.reborrow().cuts
    }
    /// Field 5: `marks` (map)
    #[must_use]
    pub fn marks(
        &self,
    ) -> &::buffa::MapView<
        '_,
        &'_ str,
        ::mediatime::wire::__buffa::view::TimestampView<'_>,
    > {
        &self.0.reborrow().marks
    }
}
impl ::core::convert::From<::buffa::OwnedView<ClipView<'static>>> for ClipOwnedView {
    fn from(inner: ::buffa::OwnedView<ClipView<'static>>) -> Self {
        ClipOwnedView(inner)
    }
}
impl ::core::convert::From<ClipOwnedView> for ::buffa::OwnedView<ClipView<'static>> {
    fn from(wrapper: ClipOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<ClipView<'static>>> for ClipOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<ClipView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Clip {
    type View<'a> = ClipView<'a>;
    type ViewHandle = ClipOwnedView;
}
